<a href="https://colab.research.google.com/github/kiiriis/CE063_ML/blob/main/Lab_03.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Implementation of Naive bayes classifier

In [ ]:
# Implementation of Naive bayes classifier

from sklearn import preprocessing
from sklearn.naive_bayes import GaussianNB, MultinomialNB

weather = ['Sunny', 'Sunny', 'Overcast', 'Rainy', 'Rainy','Rainy', 'Overcast',
'Sunny', 'Sunny', 'Rainy', 'Sunny', 'Overcast', 'Overcast', 'Rainy']

temp = ['Hot','Hot','Hot','Mild','Cool','Cool','Cool','Mild',
'Cool','Mild','Mild','Mild','Hot','Mild']

play=['No','No','Yes','Yes','Yes','No','Yes','No','Yes',
'Yes','Yes','Yes','Yes','No']

In [ ]:
le = preprocessing.LabelEncoder()

weather_encoded = le.fit_transform(weather)
print("Weather: ", weather_encoded)

Weather:  [2 2 0 1 1 1 0 2 2 1 2 0 0 1]


In [ ]:
temp_encoded = le.fit_transform(temp)
label = le.fit_transform(play)

print("Temp: ",temp_encoded)
print("Play: ",label)

Temp:  [1 1 1 2 0 0 0 2 0 2 2 2 1 2]
Play:  [0 0 1 1 1 0 1 0 1 1 1 1 1 0]


In [ ]:
features = tuple(zip(weather_encoded, temp_encoded))
print("Features: ",features)

Features:  ((2, 1), (2, 1), (0, 1), (1, 2), (1, 0), (1, 0), (0, 0), (2, 2), (2, 0), (1, 2), (2, 2), (0, 2), (0, 1), (1, 2))


In [ ]:
model = MultinomialNB()
model.fit(features,label)

MultinomialNB()

In [ ]:
predicted = model.predict([[2,2]])
print(predicted)

[1]


In [ ]:
predicted = model.predict([[2,2],[2,1]])
print(predicted)

[1 1]


##Exercise: Manually calculate output for the following cases and compare it with system’s output.
#####(1) Will you play if the temperature is ‘Hot’ and weather is ‘overcast’?
#####(2) Will you play if the temperature is ‘Mild’ and weather is ‘Sunny’?

In [ ]:
predicted = model.predict([[0,1]])
manual = 1
print("Predicted= ",predicted,"\nManual= ",manual,"\nPredicted = Manual? ",predicted[0]==manual)

Predicted=  [1] 
Manual=  1 
Predicted = Manual?  True


In [ ]:
predicted = model.predict([[2,2]])
manual = 1
print("Predicted= ",predicted,"\nManual= ",manual,"\nPredicted = Manual? ",predicted[0]==manual)

Predicted=  [1] 
Manual=  1 
Predicted = Manual?  True


# Implementation for Naive Bayes Classifier on Iris dataset

In [ ]:
import numpy as np
from sklearn import datasets
from sklearn.naive_bayes import GaussianNB

iris = datasets.load_iris()

In [ ]:
print("Features: ",iris.feature_names)
print("Labels: ",iris.target_names)
print("\nData shape: ",iris.data.shape)
print("\nTarget shape: ",iris.target.shape)

print("\nData type: ",type(iris.data))
newdata = iris.data[50:,:]
newtarget = iris.target[50:]
print("New data shape: ",newdata.shape)
print("\nNew target shape: ",newtarget.shape)

Features:  ['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']
Labels:  ['setosa' 'versicolor' 'virginica']

Data shape:  (150, 4)

Target shape:  (150,)

Data type:  <class 'numpy.ndarray'>
New data shape:  (100, 4)

New target shape:  (100,)


In [ ]:
from sklearn.model_selection import train_test_split

data_train, data_test, target_train, target_test = train_test_split(newdata,newtarget, test_size=0.30, random_state=5)

In [ ]:
import numpy as np
gnb = GaussianNB()

gnb.fit(data_train, target_train)

target_pred = gnb.predict(data_test)

In [ ]:
from sklearn import metrics

print("Accuracy: ",metrics.accuracy_score(target_test,target_pred))

Accuracy:  0.9


In [ ]:
from sklearn.metrics import confusion_matrix
confusion_matrix(target_test, target_pred)

array([[16,  1],
       [ 2, 11]])

In [ ]:
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
precision = precision_score(target_test, target_pred)
recall = recall_score(target_test, target_pred)
print('precision: {}'.format(precision))
print('recall: {}'.format(recall))

precision: 0.8888888888888888
recall: 0.9411764705882353


# Exercise for 51 <= roll number <= 75

## Task 1
Try the algo on Dataset2 - LabelEncoding of features: and Train test Division 90% − 10%

In [ ]:
from sklearn import datasets
from sklearn.naive_bayes import GaussianNB
import pandas as pd
from sklearn.preprocessing import LabelEncoder

In [ ]:
from google.colab import drive
drive.mount('/content/drive')
data = pd.read_csv('/content/drive/MyDrive/SEM-VI/ML/Dataset2.csv')
print(data)

x = data.iloc[:,:-1].values
le = LabelEncoder()
x[:,0] = le.fit_transform(x[:,0])
x[:,1] = le.fit_transform(x[:,1])
x[:,2] = le.fit_transform(x[:,2])
x[:,3] = le.fit_transform(x[:,3])
print(x)

y = data.iloc[:,-1].values
y = le.fit_transform(y)
print(y)

Mounted at /content/drive
   Outlook Temp Wind Humidity Class
0        R    H    F   Normal     N
1        R    H    T     High     N
2        O    H    F   Normal     Y
3        S    M    F   Normal     N
4        S    M    F   Normal     Y
5        S    M    T      Low     Y
6        O    C    T   Normal     Y
7        R    C    F   Normal     Y
8        R    C    F      Low     Y
9        S    M    F     High     Y
10       R    M    T     High     Y
11       O    M    T      Low     Y
12       O    H    F   Normal     Y
13       S    M    T   Normal     N
[[1 1 0 2]
 [1 1 1 0]
 [0 1 0 2]
 [2 2 0 2]
 [2 2 0 2]
 [2 2 1 1]
 [0 0 1 2]
 [1 0 0 2]
 [1 0 0 1]
 [2 2 0 0]
 [1 2 1 0]
 [0 2 1 1]
 [0 1 0 2]
 [2 2 1 2]]
[0 0 1 0 1 1 1 1 1 1 1 1 1 0]


In [ ]:
from sklearn.model_selection import train_test_split

# using random state as last 2 digits of my permanent ID
data_train, data_test, target_train, target_test = train_test_split(x,y,train_size=0.9,test_size=0.1, random_state=63)
# Random state = roll number = 63

In [ ]:
import numpy as np
gnb = GaussianNB()

gnb.fit(data_train, target_train)

target_pred = gnb.predict(data_test)
# target_pred = gnb.predict_proba(data_test)

# print(target_pred)


[2 1 0 2 0 2 0 1 1 1 1 1 1 1 1 0 1 1 0 0 2 1 0 0 2 0 0 1 1 0 2 1 0 2 2 1 0
 1 1 1 2 0 2 0 0 1 2 2 1 2 1 2 1]


In [ ]:
from sklearn import metrics

print("Accuracy: ",metrics.accuracy_score(target_test,target_pred))

Accuracy:  0.5


In [ ]:
target_pred = gnb.predict([[1,2,0,2],
                           [2,0,1,0]])
print(target_pred)

In [ ]:
from sklearn import metrics
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score

print("Accuracy: ",metrics.accuracy_score(target_test,target_pred))
precision = precision_score(target_test, target_pred)
recall = recall_score(target_test, target_pred)
print('precision: {}'.format(precision))
print('recall: {}'.format(recall))

Accuracy:  1.0
precision: 1.0
recall: 1.0


## Task 2 
Apply algorithm on digits dataset - One Hot Encoding of features: and Train test Division 65% − 35%

In [ ]:
# Getting digits data set

data=datasets.load_digits()
data.keys(), data.target

(dict_keys(['data', 'target', 'frame', 'feature_names', 'target_names', 'images', 'DESCR']),
 array([0, 1, 2, ..., 8, 9, 8]))

In [ ]:
data_train, data_test, target_train, target_test = train_test_split(iris.data, iris.target, test_size = 0.35, random_state = 0)

In [ ]:
from sklearn import metrics
gnb = GaussianNB()
gnb.fit(data_train, target_train)

target_pred = gnb.predict(data_test)
accuracy = metrics.accuracy_score(target_test, target_pred)
precision = metrics.precision_score(target_test, target_pred, average=None)
recall = metrics.recall_score(target_test, target_pred, average=None)

print('Accuracy: {}'.format(accuracy))
print('precision: {}'.format(precision))
print('recall: {}'.format(recall))

Accuracy: 0.9622641509433962
precision: [1.         0.91304348 1.        ]
recall: [1.    1.    0.875]
